/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cityguideproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MAHE
 */
public class Admin_AccomodationStatus extends javax.swing.JFrame {

    /**
     * Creates new form Admin_AccomodationStatus
     */
    Connection connect = null;
    String email = "";
    String name1 = "";
    String name = "";
    String website = "";
    public Admin_AccomodationStatus() {
        connect=SQLiteJava.dbConnector();
        initComponents();
        updateTable();
        fillCombo();
    }
    private void fillCombo(){
        try{
            String query = " select * from AccomodationStatus  ";
            PreparedStatement pst = connect.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String id = rs.getString("hotelid");
                users1.addItem(id);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    private void updateTable(){
        try{
            String query = " select hotelid, user.name as Name,public_spaces.name as Accomodation, capacity as Available_Capacity,status from AccomodationStatus,user,public_spaces where public_spaces.id=hotelid and Userid=user.id ";
            PreparedStatement pst = connect.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            users_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        users_table = new javax.swing.JTable();
        users1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        users_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(users_table);

        jLabel1.setText("ID");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Accomodation Booking Requests");

        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(users1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addGap(49, 49, 49)
                .addComponent(jButton2)
                .addGap(35, 35, 35)
                .addComponent(jButton3)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(users1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int hotelid=Integer.parseInt(users1.getSelectedItem().toString());
        String s="Update AccomodationStatus SET status=? where hotelid=?";
        String s1 = "update public_spaces set capacity = (select capacity from public_spaces where id=?)-1 where id=?;";
				try{
                                        int uid = 0;
					PreparedStatement ps = connect.prepareStatement(s);
                                        ps.setString(1,"Booking Confirmed");
					ps.setInt(2,hotelid);
					ps.executeUpdate();
                                        ps = connect.prepareStatement(s1);
                                        ps.setInt(1,hotelid);
					ps.setInt(2,hotelid);
					ps.executeUpdate();
                                        JOptionPane.showMessageDialog(null, "Request Accepted");
                                        String s2 ="select Userid from AccomodationStatus where hotelid=?";
                                        ps = connect.prepareStatement(s2);
                                        ps.setInt(1,hotelid);
                                        ResultSet rs = ps.executeQuery();
                                        while(rs.next()){
                                        uid = rs.getInt("Userid");
                                        }
                                        s1 = "select name,email_id from user where id=?";
                                        ps = connect.prepareStatement(s1);
					ps.setInt(1,uid);
                                        rs = ps.executeQuery();
                                        while(rs.next()){
                                        email = rs.getString("email_id");
                                        name1 = rs.getString("name");
                                        }
                                        s1 = "select name from public_spaces where id=?";
                                        ps = connect.prepareStatement(s1);
					ps.setInt(1,hotelid);
                                        rs = ps.executeQuery();
                                        while(rs.next()){
                                        name = rs.getString("name");
                                        }
                                        String message = "Dear "+name1+"\nYour Accomodation Booking with "+name+" has been confirmed. Please check-in anytime after 12pm and make your payment at the reception.\n\n \nRegards,\nCityGuideProject";
                                        String subject = "Confirmation of your Accomodation Booking";
                                        SendMail.mail(email, subject, message);
                                        dispose();
				}
				catch(SQLException se){
					se.printStackTrace();
				}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int hotelid=Integer.parseInt(users1.getSelectedItem().toString());
        String s="Update AccomodationStatus SET status=? where hotelid=?";
				try{
                                        int uid = 0;
					PreparedStatement ps = connect.prepareStatement(s);
                                        ps.setString(1,"Request Rejected");
					ps.setInt(2,hotelid);
					ps.executeUpdate();
                                        JOptionPane.showMessageDialog(null, "Request Rejected");
                                        String s2 ="select Userid from AccomodationStatus where hotelid=?";
                                        ps = connect.prepareStatement(s2);
                                        ps.setInt(1,hotelid);
                                        ResultSet rs = ps.executeQuery();
                                        while(rs.next()){
                                        uid = rs.getInt("Userid");
                                        }
                                        String s1 = "select name,email_id from user where id=?";
                                        ps = connect.prepareStatement(s1);
					ps.setInt(1,uid);
                                        rs = ps.executeQuery();
                                        while(rs.next()){
                                        email = rs.getString("email_id");
                                        name1 = rs.getString("name");
                                        }
                                        s1 = "select name from public_spaces where id=?";
                                        ps = connect.prepareStatement(s1);
					ps.setInt(1,hotelid);
                                        rs = ps.executeQuery();
                                        while(rs.next()){
                                        name = rs.getString("name");
                                        }
                                        String message = "Dear "+name1+"\nYour Accomodation Booking with "+name+" has been declined. Please book a different Accomodation stay.\n\n \nRegards,\nCityGuideProject";
                                        String subject = "Declination of your Accomodation Booking";
                                        SendMail.mail(email, subject, message);
                                        dispose();
				}
				catch(SQLException se){
					se.printStackTrace();
				}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_AccomodationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_AccomodationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_AccomodationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_AccomodationStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_AccomodationStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> users1;
    private javax.swing.JTable users_table;
    // End of variables declaration//GEN-END:variables
}
